// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	DMRelation string
	DMVersion  string
}{
	DMRelation: "dm_relation",
	DMVersion:  "dm_version",
}
