// Package models contains the types for schema 'dev_emf'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"database/sql/driver"
	"encoding/csv"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"
)

// DmRelation represents a row from 'dev_emf.dm_relation'.
type DmRelation struct {
	FromContent sql.NullInt64 `json:"from_content"` // from_content
	ToContent sql.NullInt64 `json:"to_content"` // to_content
	RelationType sql.NullString `json:"relation_type"` // relation_type
	Priority sql.NullInt64 `json:"priority"` // priority
	Identifier sql.NullString `json:"identifier"` // identifier
	Comment sql.NullString `json:"comment"` // comment
	RemoteID sql.NullString `json:"remote_id"` // remote_id
}



