// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	DMArticle  string
	DMFolder   string
	DMLocation string
	DMUser     string
	DMVersion  string
}{
	DMArticle:  "dm_article",
	DMFolder:   "dm_folder",
	DMLocation: "dm_location",
	DMUser:     "dm_user",
	DMVersion:  "dm_version",
}
