// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	DMLocation string
	DMVersion  string
}{
	DMLocation: "dm_location",
	DMVersion:  "dm_version",
}
